using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace salmar_d365_mtps_convertor
{
    public class PURCHPURCHASEORDERHEADERV2ENTITY
    {
        //Autogenerated
        //<PURCHASEORDERNUMBER>000005</PURCHASEORDERNUMBER>

        //<ACCOUNTINGDATE>2021-12-09T00:00:00+00:00</ACCOUNTINGDATE>
        //<AREPRICESINCLUDINGSALESTAX>0</AREPRICESINCLUDINGSALESTAX>
        //<CURRENCYCODE>NOK</CURRENCYCODE>
        //
        //<DEFAULTRECEIVINGSITEID>STD</DEFAULTRECEIVINGSITEID>
        //<DEFAULTRECEIVINGWAREHOUSEID/>
        //<DOCUMENTAPPROVALSTATUS>40</DOCUMENTAPPROVALSTATUS>
        //<FIXEDDUEDATE>1900-01-01T00:00:00+00:00</FIXEDDUEDATE>
        //<LANGUAGEID>nb-NO</LANGUAGEID>
        //<ORDERVENDORACCOUNTNUMBER>000003</ORDERVENDORACCOUNTNUMBER>
        //<PURCHASEORDERNAME>Test vendor</PURCHASEORDERNAME>
        //<PURCHASEORDERSTATUS>2</PURCHASEORDERSTATUS>
        //<REQUESTEDDELIVERYDATE>2021-12-09T00:00:00+00:00</REQUESTEDDELIVERYDATE>
        //<SALESTAXGROUPCODE>LPL</SALESTAXGROUPCODE>
        //<MBSMARITECHINVOICEID/>
        //<MBSMARITECHPAYMID/>


        //<DEFAULTLEDGERDIMENSIONDISPLAYVALUE>--104411-----311---</DEFAULTLEDGERDIMENSIONDISPLAYVALUE>
        //<SALESTAXITEMGROUPCODE/>
        //<VENDORPOSTINGPROFILEID>STD</VENDORPOSTINGPROFILEID>


        //public string PURCHASEORDERNUMBER { get; set; }
        //public string ACCOUNTINGDATE { get; set; }
        public int AREPRICESINCLUDINGSALESTAX { get; set; }
        public string CURRENCYCODE { get; set; }
        //public string DEFAULTLEDGERDIMENSIONDISPLAYVALUE { get; set; }
        public string DEFAULTRECEIVINGSITEID { get; set; }
        public string DEFAULTRECEIVINGWAREHOUSEID { get; set; }
        public string DOCUMENTAPPROVALSTATUS { get; set; }
        public string INVOICEVENDORACCOUNTNUMBER { get; set; }
        public string FIXEDDUEDATE { get; set; }
        public string LANGUAGEID { get; set; }
        public string ORDERVENDORACCOUNTNUMBER { get; set; }
        public string PURCHASEORDERNAME { get; set; }
        public string PURCHASEORDERSTATUS { get; set; }
        public string REQUESTEDDELIVERYDATE { get; set; }
        public string SALESTAXGROUPCODE { get; set; }
        public string MBSMARITECHINVOICEID { get; set; }
        public string MBSMARITECHPAYMID { get; set; }
        public string VENDORORDERREFERENCE { get; set; }
        public decimal MBSFIXEDEXCHRATE { get; set; }
        public string MBSFROMMARITECH { get; set; }
        public string MBSCURRENCYHEDGE { get; set; }
        //New fields 2022-03-29
        public decimal MBSINVOICETOTAL { get; set; }
        public string MBSMARITECHINVOICEDATE { get; set; }
        
        //public string SALESTAXITEMGROUPCODE { get; set; }
        //public string VENDORPOSTINGPROFILEID { get; set; }
        
        //KPMGNO-1256 (PO med flere fakturaer)
        public string PurchaseOrderPoolId { get; set; }

        //KPMGNO-1135 (Column 'MBSFixedExchRate' on purchase order doesn't consider conversion factor) 2022-09-30
        public int MBSMARITECHFACTOR { get; set; }
        public decimal MBSMARITECHEXCHAGERATE { get; set; }

        [XmlElement("PURCHPURCHASEORDERLINEV2ENTITY")]
        public List<PURCHPURCHASEORDERLINEV2ENTITY> PurchaseOrderLineV2Entities { get; set; }

    }
    public class PURCHPURCHASEORDERLINEV2ENTITY
    {
        //Autogenerated
        //<PURCHASEORDERNUMBER>000005</PURCHASEORDERNUMBER>
        //<INVENTORYLOTID>000009</INVENTORYLOTID>

        //<LINENUMBER>1</LINENUMBER>
        //<DEFAULTLEDGERDIMENSIONDISPLAYVALUE>--104411-----311---</DEFAULTLEDGERDIMENSIONDISPLAYVALUE>
        //<ITEMNUMBER>31000</ITEMNUMBER>
        //<LINEAMOUNT>250.000000</LINEAMOUNT>
        //<LINEDESCRIPTION>Salgsinntekt helfisk, avgfri</LINEDESCRIPTION>
        //<DEFAULTLEDGERDIMENSIONDISPLAYVALUE/>
        //<ORDEREDPURCHASEQUANTITY>10.000000</ORDEREDPURCHASEQUANTITY>
        //<PURCHASEORDERLINESTATUS>2</PURCHASEORDERLINESTATUS>
        //<PURCHASEPRICE>25.000000</PURCHASEPRICE>
        //<PURCHASEPRICEQUANTITY>1.000000000000</PURCHASEPRICEQUANTITY>
        //<PURCHASEUNITSYMBOL>stk</PURCHASEUNITSYMBOL>
        //<REQUESTEDDELIVERYDATE>2021-12-09T00:00:00+00:00</REQUESTEDDELIVERYDATE>
        //<SALESTAXGROUPCODE>LPL</SALESTAXGROUPCODE>
        //<SALESTAXITEMGROUPCODE/>
        //<ITEMNUMBER>43001</ITEMNUMBER>

        //??? <CALCULATELINEAMOUNT>1</CALCULATELINEAMOUNT>
        //??? <MAINACCOUNTIDDISPLAYVALUE/>
        //??? <RECEIVINGSITEID>411</RECEIVINGSITEID>
        //??? <SKIPCREATEAUTOCHARGES>1</SKIPCREATEAUTOCHARGES>


        //public string PURCHASEORDERNUMBER { get; set; }
        //public string INVENTORYLOTID { get; set; }
        public int LINENUMBER { get; set; }
        public string ITEMNUMBER { get; set; }
        public decimal LINEAMOUNT { get; set; }
        public string LINEDESCRIPTION { get; set; }
        public string DEFAULTLEDGERDIMENSIONDISPLAYVALUE { get; set; }
        public decimal ORDEREDPURCHASEQUANTITY { get; set; }
        public string PURCHASEORDERLINESTATUS { get; set; }
        public decimal PURCHASEPRICE { get; set; }
        public decimal PURCHASEPRICEQUANTITY { get; set; }
        public string PURCHASEUNITSYMBOL { get; set; }
        public string REQUESTEDDELIVERYDATE { get; set; }
        public string SALESTAXGROUPCODE { get; set; }
        public string SALESTAXITEMGROUPCODE { get; set; }

    }
}
